[package]
name = "day1_2"
version = "0.1.0"
authors = ["Joshua Yates"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
